USE MOVIES

-- 1
SELECT NAME, BIRTHDATE
FROM MOVIESTAR
WHERE GENDER = 'F' AND NAME LIKE '%e%'
ORDER BY BIRTHDATE DESC, NAME ASC

-- 2
USE PC

-- Different price = different configs
SELECT p.MAKER, COUNT(DISTINCT l.PRICE) AS CONFIGS
FROM PRODUCT p
    LEFT OUTER JOIN LAPTOP l ON p.MODEL = l.MODEL
GROUP BY p.MAKER

-- 3
-- Different price = different configs
SELECT p1.MAKER, l.MODEL, COUNT(DISTINCT l.PRICE) AS CONFIGS
FROM PRODUCT p1
    JOIN PRODUCT p2 ON p1.TYPE != p2.TYPE AND p1.TYPE = 'PC' AND p2.TYPE = 'Laptop'
    LEFT OUTER JOIN LAPTOP l ON p2.MODEL = l.MODEL
GROUP BY l.MODEL, p1.MAKER

-- 4
USE SHIPS

SELECT DISTINCT c.COUNTRY
FROM CLASSES c
    LEFT OUTER JOIN SHIPS s ON s.CLASS = c.CLASS
    LEFT OUTER JOIN OUTCOMES o ON s.NAME = o.SHIP
WHERE s.LAUNCHED = 1942 AND RESULT = 'ok' AND NUMGUNS = 8