#!/usr/bin/env python3

import os
import sys

def main():
    # get current script path
    script_path = os.path.realpath(__file__)

    # get path to do package
    package_path = os.path.join(os.path.dirname(script_path), "python", "site-packages")

    # make do package available
    sys.path.append(package_path)

    import do
    do.main()


if __name__ == '__main__':
    main()
