#!/bin/bash

# Set environment variables
VENV_DIR="pvenv"

# Step 1: Create and activate Python virtual environment
if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
fi

export BUILD_DIR="build"

# Activate virtual environment
source "$VENV_DIR/bin/activate"
