USE PC

-- 1
SELECT AVG(SPEED) AS AVG_SPEED
FROM PC

-- 2
SELECT p.MAKER, AVG(SCREEN) AS AVG_SCREEN
FROM LAPTOP l
    JOIN PRODUCT p ON p.MODEL = l.MODEL
GROUP BY p.MAKER

-- 3
SELECT AVG(SPEED)
FROM LAPTOP
WHERE PRICE > 1000

-- 4
SELECT AVG(PRICE) AS AVG_PRICE
FROM PRODUCT p
    JOIN PC PC ON p.MODEL = PC.MODEL
WHERE MAKER = 'A'

-- 5
SELECT AVG(PRICE) AS AVG_PRICE
FROM (SELECT PRICE
      FROM PRODUCT p
        JOIN PC ON p.MODEL = PC.MODEL
      WHERE MAKER = 'B'
      UNION ALL
      SELECT PRICE
      FROM PRODUCT p
        JOIN LAPTOP ON p.MODEL = LAPTOP.MODEL
      WHERE MAKER = 'B') u

-- 6
SELECT SPEED, AVG(PRICE) AS AVG_PRICE
FROM PC
GROUP BY SPEED

-- 7
SELECT MAKER
FROM PRODUCT
WHERE TYPE = 'PC'
GROUP BY MAKER
HAVING COUNT(*) >= 3

-- 8
SELECT DISTINCT p.MAKER
FROM PRODUCT p
    JOIN PC pc ON pc.MODEL = p.MODEL
WHERE PRICE = (SELECT MAX(PRICE)
               FROM PC)

-- 9
SELECT SPEED, AVG(PRICE) AS AVG_PRICE
FROM PC
WHERE SPEED > 800
GROUP BY SPEED

-- 10
SELECT AVG(HD) AS AVG_HD
FROM PRODUCT
    JOIN PC on PRODUCT.MODEL = PC.MODEL
WHERE MAKER IN (SELECT MAKER
                FROM PRODUCT
                WHERE TYPE = 'Printer')
-- 11
SELECT SCREEN, MAX(PRICE) - MIN(PRICE) AS PRICE_DIFF
FROM LAPTOP
GROUP BY SCREEN
