USE PC

-- 1
SELECT p.MAKER, l.SPEED
FROM LAPTOP l
    JOIN PRODUCT p ON p.MODEL = l.MODEL
WHERE HD >= 9

-- 2
SELECT u.MODEL, u.PRICE
FROM PRODUCT p
    JOIN (SELECT MODEL, PRICE
          FROM PC
          UNION
          SELECT MODEL, PRICE
          FROM LAPTOP
          UNION
          SELECT MODEL, PRICE
          FROM PRINTER) u ON p.MODEL = u.MODEL
WHERE p.MAKER = 'B'
ORDER BY PRICE DESC

-- 

SELECT PC.MODEL, PRICE
FROM PC
    JOIN PRODUCT ON PC.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER = 'B'

UNION

SELECT LAPTOP.MODEL, PRICE
FROM LAPTOP
    JOIN PRODUCT ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER = 'B'

UNION

SELECT PRINTER.MODEL, PRICE
FROM PRINTER
    JOIN PRODUCT ON PRINTER.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER = 'B' ORDER BY PRICE DESC

-- 3
SELECT DISTINCT p1.HD
FROM PC p1
    JOIN PC p2 ON p1.CODE != p2.CODE
WHERE p1.HD = p2.HD

-- 4
SELECT p1.MODEL, p2.MODEL
FROM PC p1
    JOIN PC p2 ON p1.SPEED = p2.SPEED AND p1.RAM = p2.RAM
WHERE p1.MODEL < p2.MODEL

SELECT p1.MODEL, p2.MODEL
FROM PC p1
    JOIN PC p2 ON p1.MODEL < p2.MODEL
WHERE p1.SPEED = p2.SPEED AND p1.RAM = p2.RAM

-- 5
SELECT DISTINCT p1.MAKER
FROM PC pc1
    JOIN PC pc2 ON pc1.CODE != pc2.CODE
    JOIN PRODUCT p1 ON pc1.MODEL = p1.MODEL
    JOIN PRODUCT p2 ON pc2.MODEL = p2.MODEL
WHERE pc1.SPEED >= 500 AND pc2.SPEED >= 500 AND p1.MAKER = p2.MAKER
