USE SHIPS

-- 1
SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM SHIPS s
    JOIN CLASSES c ON c.CLASS = s.CLASS

-- 2
SELECT DISTINCT SHIP
FROM OUTCOMES o
    JOIN BATTLES b ON b.NAME = o.BATTLE
WHERE YEAR(b.DATE) = 1942

-- 3
SELECT c.COUNTRY, s.NAME
FROM CLASSES c
    JOIN SHIPS s ON c.CLASS = s.CLASS
    LEFT OUTER JOIN OUTCOMES o ON s.NAME = o.SHIP
WHERE o.SHIP IS NULL

-- Допълнителна задача (additional task)
SELECT DISTINCT c.CLASS
FROM CLASSES c
    LEFT OUTER JOIN SHIPS s ON s.CLASS = c.CLASS AND LAUNCHED > 1921
WHERE s.NAME IS NULL

--

SELECT CLASS
FROM CLASSES
WHERE CLASS NOT IN (SELECT CLASS
                    FROM SHIPS
                    WHERE LAUNCHED > 1921)
