USE MOVIES

-- 1
SELECT TITLE, YEAR, NAME, ADDRESS
FROM MOVIE
    JOIN STUDIO ON NAME = STUDIONAME
WHERE LENGTH > 120

-- 2
SELECT DISTINCT STUDIONAME, STARNAME
FROM MOVIE
    JOIN STARSIN ON TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
ORDER BY STUDIONAME

-- 3
SELECT DISTINCT me.NAME
FROM MOVIE m
    JOIN STARSIN s ON m.TITLE = s.MOVIETITLE AND m.YEAR = s.MOVIEYEAR
    JOIN MOVIEEXEC me ON me.CERT# = m.PRODUCERC#
WHERE s.STARNAME = 'Harrison Ford'

-- 4
SELECT DISTINCT ms.NAME
FROM MOVIE m
    JOIN STARSIN s ON m.TITLE = s.MOVIETITLE AND m.YEAR = s.MOVIEYEAR
    JOIN MOVIESTAR ms ON s.STARNAME = ms.NAME
WHERE ms.GENDER = 'F' AND m.STUDIONAME = 'MGM'

-- 5
SELECT e.NAME, m1.TITLE
FROM MOVIE m1
    JOIN MOVIE m2 ON m2.TITLE = 'Star Wars' AND m2.YEAR = 1977
    JOIN MOVIEEXEC e ON e.CERT# = m1.PRODUCERC#
WHERE m1.PRODUCERC# = m2.PRODUCERC#

--

SELECT e.NAME, m.TITLE
FROM MOVIE m
    JOIN MOVIEEXEC e ON e.CERT# = m.PRODUCERC#
WHERE m.PRODUCERC# = (SELECT PRODUCERC#
                      FROM MOVIE
                      WHERE TITLE = 'Star Wars' AND YEAR = 1977)


-- 6
SELECT NAME
FROM MOVIESTAR
    LEFT OUTER JOIN STARSIN ON NAME = STARNAME 
WHERE STARNAME IS NULL
