-- 1
CREATE VIEW BRITISHSHIPS
AS
    SELECT s.NAME, c.CLASS, c.TYPE, c.NUMGUNS, c.BORE, c.DISPLACEMENT, s.LAUNCHED
    FROM CLASSES c
        JOIN SHIPS s ON c.CLASS = s.CLASS
    WHERE c.COUNTRY = 'Gt.Britain'

GO

-- 2
SELECT NUMGUNS, DISPLACEMENT
FROM BRITISHSHIPS
WHERE LAUNCHED = 1917

DROP VIEW BRITISHSHIPS
GO

-- 3
SELECT NUMGUNS, DISPLACEMENT
FROM  ( SELECT s.NAME, c.CLASS, c.TYPE, c.NUMGUNS, c.BORE, c.DISPLACEMENT, s.LAUNCHED
        FROM CLASSES c
            JOIN SHIPS s ON c.CLASS = s.CLASS
        WHERE c.COUNTRY = 'Gt.Britain') n
WHERE n.LAUNCHED = 1917

-- 4
USE SHIPS
GO

CREATE VIEW AVERAGEMAXES
AS
    SELECT AVG(m.MAXDISPLACEMENT) AS MAX_AVG
    FROM CLASSES c
        JOIN (  SELECT COUNTRY, MAX(DISPLACEMENT) AS MAXDISPLACEMENT
                FROM CLASSES
                GROUP BY COUNTRY) m ON c.COUNTRY = m.COUNTRY AND c.DISPLACEMENT = m.MAXDISPLACEMENT
GO

DROP VIEW AVERAGEMAXES
GO

-- 5
CREATE VIEW SUNKEDSHIPS
AS
    SELECT BATTLE, SHIP
    FROM OUTCOMES
    WHERE RESULT = 'sunk'
GO

-- 6
ALTER TABLE OUTCOMES
ADD CONSTRAINT DC_OUTCOMES_RESULT DEFAULT 'sunk' FOR RESULT
GO

INSERT INTO SUNKEDSHIPS(BATTLE, SHIP)
VALUES ('Guadalcanal', 'California')
GO

SELECT * FROM SUNKEDSHIPS

ALTER TABLE OUTCOMES
DROP CONSTRAINT DC_OUTCOMES_RESULT
GO

DROP VIEW SUNKEDSHIPS
GO

-- 7
CREATE VIEW NUMGUNS9
AS
    SELECT *
    FROM CLASSES
    WHERE NUMGUNS >= 9
WITH CHECK OPTION
GO

UPDATE NUMGUNS9 SET NUMGUNS = 15
WHERE CLASS = 'Iowa'

-- Следващото не работи, заради WITH CHECK OPTION. 
-- Подобна модификация би извадила обновявания запис извън обсега на изгледа.
UPDATE NUMGUNS9 SET NUMGUNS = 5
WHERE CLASS = 'Iowa'
GO

-- 8
ALTER VIEW NUMGUNS9
AS
    SELECT *
    FROM CLASSES
    WHERE NUMGUNS >= 9
GO

DROP VIEW NUMGUNS9
GO

-- 9
CREATE VIEW BATTLELIST
AS
    SELECT BATTLE
    FROM OUTCOMES o
        JOIN SHIPS s ON o.SHIP = s.NAME
        JOIN CLASSES c ON s.CLASS = c.CLASS 
    WHERE c.NUMGUNS < 9
    GROUP BY BATTLE
    HAVING COUNT(*) >= 3 AND SUM(CASE RESULT WHEN 'damaged' THEN 1 ELSE 0 END) >= 1
GO

SELECT * FROM BATTLELIST

DROP VIEW BATTLELIST
GO