CC := cc
SYSHDR_SOURCE := ../syshdr.c

# TODO: make it generic

.PHONY: task1
task1:
	$(CC) $(SYSHDR_SOURCE) task1.c -o task1 && ./task1

.PHONY: task2
task2:
	$(CC) $(SYSHDR_SOURCE) task2.c -o task2 && ./task2

.PHONY: task3
task3:
	$(CC) $(SYSHDR_SOURCE) task3.c -o task3 && ./task3

.PHONY: task4
task4:
	$(CC) $(SYSHDR_SOURCE) task4.c -o task4 && ./task4

.PHONY: task5
task5:
	$(CC) $(SYSHDR_SOURCE) task5.c -o task5 && ./task5

.PHONY: task6
task6:
	$(CC) $(SYSHDR_SOURCE) task6.c -o task6 && ./task6

.PHONY: clean
clean:
	rm -f *.o task1 task2 task3 task4 task5 task6 a.out